"use client";

import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, ShieldAlert } from "lucide-react";
import ErrorPanel from "@/components/ErrorPanel";
import LoadingPanel from "@/components/LoadingPanel";
import PageHeader from "@/components/PageHeader";
import { getOpenAlerts } from "@/lib/data";
import { createLiveTick } from "@/lib/liveStore";
import { supabase } from "@/lib/supabase";

export default function AlertsPage() {
  const [alerts,    setAlerts]    = useState([]);
  const [loading,   setLoading]   = useState(true);
  const [error,     setError]     = useState(null);
  const [simActive, setSimActive] = useState(false);
  const [tickCount, setTickCount] = useState(0);

  const loadAlerts = () => {
    setLoading(true);
    getOpenAlerts(100).then(setAlerts).catch(setError).finally(() => setLoading(false));
  };

  useEffect(loadAlerts, []);

  // Track simulation on/off state (set from the header "Start Simulation" button)
  useEffect(() => {
    setSimActive(localStorage.getItem("trend-trackers-sim-active") === "true");
    const handler = (event) => setSimActive(Boolean(event.detail));
    window.addEventListener("trend-trackers-sim-toggle", handler);
    return () => window.removeEventListener("trend-trackers-sim-toggle", handler);
  }, []);

  // While simulation is active, generate live ticks on the same cadence as
  // the dashboard, and push MISPLACED / STOLEN events straight into the
  // alert feed so this page updates in real time alongside the simulation.
  useEffect(() => {
    if (!simActive) return undefined;
    const interval = window.setInterval(() => {
      setTickCount((count) => {
        const next = count + 1;
        const tick = createLiveTick(next);

        if (tick.event_type === "MISPLACED" || tick.event_type === "STOLEN") {
          const alertType = tick.event_type === "MISPLACED" ? "MISPLACEMENT" : "THEFT_ALERT";
          const liveAlert = {
            id: `live-alert-${tick.id}`,
            alert_type: alertType,
            product_name: tick.product_name,
            rfid_tag_id: tick.rfid_tag_id,
            from_rack: tick.from_rack,
            to_rack: tick.to_rack,
            message: tick.description,
            created_at: tick.created_at,
          };
          setAlerts((current) => [liveAlert, ...current].slice(0, 150));
        }

        return next;
      });
    }, 1800);
    return () => window.clearInterval(interval);
  }, [simActive]);

  const misplaced = useMemo(() => alerts.filter((alert) => String(alert.alert_type || alert.type || "").toUpperCase().includes("MISPLACE")), [alerts]);
  const theft = useMemo(() => alerts.filter((alert) => String(alert.alert_type || alert.type || "").toUpperCase().includes("THEFT")), [alerts]);

  async function markResolved(alert) {
    // Live (simulation-only) alerts aren't in Supabase yet — just drop them locally.
    if (String(alert.id || "").startsWith("live-alert-")) {
      setAlerts((current) => current.filter((a) => a.id !== alert.id));
      return;
    }
    const idColumn = alert.id ? "id" : alert.alert_id ? "alert_id" : null;
    if (!idColumn) return;
    await supabase.from("alerts").update({ status: "RESOLVED", resolved: true, resolved_at: new Date().toISOString() }).eq(idColumn, alert[idColumn]);
    loadAlerts();
  }

  return (
    <>
      <PageHeader
        eyebrow="Exception Center"
        title="Alerts"
        description="Review misplaced items, theft alerts, and alert history generated by RFID movement intelligence."
      />

      {simActive && (
        <div className="mb-6 flex items-center gap-2 rounded-lg border border-green-200 bg-green-50 px-4 py-2.5 text-sm font-medium text-green-700">
          <span className="h-2 w-2 animate-pulse rounded-full bg-green-500" />
          Live simulation running — alerts are updating in real time.
        </div>
      )}

      {error ? <ErrorPanel error={error} /> : null}
      {loading ? <LoadingPanel label="Loading alert stream..." /> : null}

      {!loading && !error ? (
        <div className="grid gap-4 xl:grid-cols-[1fr_1fr]">
          <AlertColumn title="Misplaced Items" icon={AlertTriangle} tone="yellow" alerts={misplaced} onResolve={markResolved} />
          <AlertColumn title="Theft Alerts" icon={ShieldAlert} tone="red" alerts={theft} onResolve={markResolved} />
          <div className="xl:col-span-2">
            <AlertColumn title="Alert History" icon={AlertTriangle} tone="cyan" alerts={alerts} onResolve={markResolved} />
          </div>
        </div>
      ) : null}
    </>
  );
}

function AlertColumn({ title, icon: Icon, tone, alerts, onResolve }) {
  const colors = {
    yellow: "border-yellow-200 text-yellow-600",
    red: "border-red-200 text-red-600",
    cyan: "border-brand-200"
  };

  return (
    <section className="panel rounded-lg p-5">
      <div className="mb-4 flex items-center justify-between">
        <h2 className="text-sm font-black uppercase tracking-[0.18em] text-stone-900">{title}</h2>
        <span className={`flex items-center gap-2 rounded-lg border px-3 py-1 text-xs font-bold ${colors[tone]}`}>
          <Icon size={15} />
          {alerts.length}
        </span>
      </div>

      <div className="space-y-3">
        {alerts.map((alert, index) => (
          <div key={alert.id || alert.alert_id || index} className={`rounded-lg border-l-4 bg-stone-50 p-4 ${colors[tone]}`}>
            <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
              <div>
                <div className="flex flex-wrap items-center gap-2">
                  <span className="text-xs font-black uppercase">{alert.alert_type || alert.type || "ALERT"}</span>
                  <span className="text-xs text-stone-400">{formatTime(alert.created_at)}</span>
                </div>
                <p className="mt-2 font-bold text-stone-900">{alert.product_name || alert.message || "Inventory alert"}</p>
                <p className="mt-1 text-sm text-stone-500">
                  {alert.rfid_tag_id || alert.item_id} {alert.from_rack || alert.to_rack ? `· ${alert.from_rack || "unknown"} to ${alert.to_rack || "unknown"}` : ""}
                </p>
                {alert.message ? <p className="mt-1 text-sm text-stone-400">{alert.message}</p> : null}
              </div>
              <button
                onClick={() => onResolve(alert)}
                className="min-h-9 rounded-lg border border-stone-200 bg-stone-50 px-3 text-xs font-bold text-stone-900 hover:bg-stone-50"
              >
                Resolve
              </button>
            </div>
          </div>
        ))}
        {!alerts.length ? <p className="rounded-lg border border-stone-200 bg-stone-50 p-4 text-sm text-stone-400">No alerts found.</p> : null}
      </div>
    </section>
  );
}

function formatTime(value) {
  if (!value) return "Live";
  return new Date(value).toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" });
}
